[ids]
ids_node ansible_host=34.250.74.247

[victims]
victim-web ansible_host=54.75.132.154
victim-db ansible_host=18.202.23.61
victim-file ansible_host=34.241.119.132

[soc]
soc_node ansible_host=108.131.195.208

[kali]
kali-attack ansible_host=3.252.104.38 ansible_user=kali

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=terraform/nids-pfe-key.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
